### ISSUE TITLE
Add Pending Requests and Group Matching

### ISSUE THREAD

**Issue by egreisz** [UWSocialComputing/Vitamin-CS-Project#4]
Users should be able to create a pending request for a specific show they want to watch. When enough of these are made for a specific show, we then match these users into a group. 
Requirements:
- [ ] frontend widget to make a pending request.
  - Only needs the ability to select a show (list of options can be hard-coded for now)
  -  In the future, we can add cadence if time permits (which I doubt it will at this point)
- [x] backend endpoint to make a pending request for a specific user
  - needs to be stored in the database
  - needs to check the database to see if there are enough other requests for this show. If so, remove these from the database and make a Stream channel with these users in it

**Comment by shaurya2109** [comment]
Backend To Do for this Task:
- [ ] Testing
- [ ] Reducing redundancy
